#!/usr/bin/python
# -*- coding: utf-8 -*-

import sys, re, os
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '../..')))

try: from lib import preload
except:
    print "E: Can't connect to library!"
    sys.exit()

from lib import libgenerator
import pwikipedia as pywikibot

def main():
    for page in libgenerator.CatGenerator(u"บทความที่มีเนื้อหาน้อยมาก"):
        original_content = page.get(get_redirect = True)
        content = original_content
        content = pywikibot.removeCategoryLinks(content)
        content = pywikibot.removeLanguageLinks(content)
        content = re.sub(u"\s+", u" ", content)
        while True:
            newcontent = re.sub(ur"\{\{(?:(?!\{\{|\}\}).)*\}\}", u"", content, flags = re.DOTALL)
            if content == newcontent: break
            content = newcontent
        content = re.sub(ur"\{\|.*?\|\}", u"", content, flags = re.DOTALL)
        content = re.sub(ur"<ref.*?</ref>", u"", content, flags = re.DOTALL)
        content = re.sub(ur"(?<!\[)\[(?!\[).*?\]", u"", content, flags = re.DOTALL)
        pywikibot.output(u"%s : %d" % (page.title(), len(content)))
        if len(content) >= 1000:
            pywikibot.output(u">>> ยาวแล้ว")
            content = original_content.replace(u"{{สั้นมาก}}", u"")
            if content != original_content:
                page.put(content, u"บทความมีความยาวพอควรแล้ว นำป้ายสั้นมากออก")

if __name__ == "__main__":
    args, site, conf = preload.pre(u"remove veryshort tag", lock = True)
    try: main()
    except: preload.posterror()
    preload.post()
