#!/bin/bash

current_dir="$(dirname $0)"

elif test "$1" == "-clearlog"; then
    file="$current_dir"/config/data.cfg
    basepath="$(grep -o -P "(?<=PYWIKI: ).*" $file)"
    mkdir "${basepath}/logs/new"
    mv "${basepath}/logs"/*.log "${basepath}/logs/new/"
    mv "${basepath}/logs/old/" "${basepath}/logs/new/"
    mv "${basepath}/logs/new/" "${basepath}/logs/old"
else
    echo "Terminating! Your argument is invalid!"
fi
