#!/bin/bash

current_dir="$(dirname $0)"

run(){
    scriptname="$1"
    shift
    if ! test -e "${current_dir}/script/$scriptname"; then
        echo "!!! ชื่อสคริปต์ไม่ถูกต้อง"
        exit
    fi
    bot="$(ls ${current_dir}/script/$scriptname/'$'* | grep -o -P '(?<=/\$).*')"
    if test -z "$bot"; then
        echo "!!! ไม่มีข้อมูลบอต"
        exit
    fi
    echo "ดำเนินการโดย $bot"
    cd bots/"$bot"
    for last; do true; done
    (test "$last" == "_timestamp_") && python ./../../pywikipedia/replace.py -page:User:Nullzerobot/status -regex "(?s)^.*$" "$RANDOM" -summary:ลงเวลา -always
    ./../../script/"$scriptname/$scriptname" "$@"
}

createuser(){
    botname="$1"
    if test -z "$botname"; then
        echo "!!! โปรดระบุชื่อบอต"
        exit
    fi
    cd pywikipedia
    python generate_user_files.py
    cd ../bots
    mkdir "$botname"
    cd "$botname"
    ln -s ../../pywikipedia/families
    ln -s ../../pywikipedia/userinterfaces
    mv ../../pywikipedia/user-config.py .
    python ../../pywikipedia/login.py
}

clearlog(){
    file="$current_dir"/config/data.cfg
    basepath="$(grep -o -P "(?<=PYWIKI: ).*" $file)"
    mkdir "${basepath}/logs/new"
    mv "${basepath}/logs"/*.log "${basepath}/logs/new/"
    mv "${basepath}/logs/old/" "${basepath}/logs/new/"
    mv "${basepath}/logs/new/" "${basepath}/logs/old"
}


cd "$current_dir"
mode="$1"
shift
case "$mode" in
"ts")
    run "$@" "_timestamp_"
    echo "$>> รันสคริปต์เรียบร้อย"
    ;;
"run" | "r")
    run "$@"
    echo "$>> รันสคริปต์เรียบร้อย"
    ;;
"create" | "c")
    createuser "$@"
    echo "$>> สร้างไอดีเรียบร้อย"
    ;;
"setup" | "s")
    svn checkout http://svn.wikimedia.org/svnroot/pywikipedia/trunk/pywikipedia/ pywikipedia
    echo "$>> ติดตั้งเรียบร้อย"
    ;;
"pyc")
    find "${current_dir}" -type f | grep -P "\.pyc$" | xargs rm
    echo "$>> ลบไฟล์ pyc"
    ;;
"git")
    git rm $(git ls-files --deleted)
    echo "$>> ลบไฟล์ gitrm"
    ;;
"log")
    clearlog
    ;;
*)
    echo "!!! พารามิเตอร์ไม่ถูกต้อง"
    ;;
esac
