#!/usr/bin/python
# -*- coding: utf-8 -*-

import sys, os
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '../..')))

try: from lib import preload
except:
    print "เรียกใช้ไลบรารีไม่ได้ จบการทำงาน!"
    sys.exit()

import pwikipedia as pywikibot

def main():
    text = u"{{ทดลองเขียน}}<!-- กรุณาอย่าแก้ไขบรรทัดนี้ ขอบคุณครับ/ค่ะ -- Please leave this line as they are. Thank you! -->\n"
    page = pywikibot.Page(site, u"วิกิพีเดีย:ทดลองเขียน")
    page.put(text, u"ล้างหน้าอัตโนมัติด้วยบอต")
    # all sanbox pages can be obtained from miscellaneous.sandboxPages

if __name__ == "__main__":
    args, site = preload.pre(u"ล้างกระบะทราย", lock = True)
    try: main()
    except: preload.posterror()
    preload.post()
