#!/usr/bin/python
# -*- coding: utf-8 -*-
"""Clear sandbox! Nothing more than this."""

__version__ = "1.0.1"
__author__ = "Sorawee Porncharoenwase"

import sys, os
sys.path.append(os.path.abspath("../.."))
from lib import preload
import pwikipedia as pywikibot

def main():
    if conf.modeClear == "only":
        pagelist = [preload.conf.sandboxPages[0]]
    else:
        pagelist = preload.conf.sandboxPages
    for title in pagelist:
        page = pywikibot.Page(site, title)
        page.put(conf.text, conf.summary)

if __name__ == "__main__":
    args, site, conf = preload.pre(u"clear sandbox", lock = True)
    try:
        main()
    except:
        preload.posterror()
    else:
        preload.post()
