#!/usr/bin/python
# -*- coding: utf-8 -*-

import sys, os
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '../..')))

try: from lib import preload
except:
    print "E: Can't connect to library!"
    sys.exit()

import pwikipedia as pywikibot

def main():
    for title in conf.pagelist:
        page = pywikibot.Page(site, title)
        page.put(conf.text, conf.summary)

if __name__ == "__main__":
    args, site, conf = preload.pre(u"clear sandbox", lock = True)
    try: main()
    except: preload.posterror()
    preload.post()
