#!/usr/bin/python
# -*- coding: utf-8  -*-
"""
Clean pages which are given in argument list. If there is no argument,
it will clean sample text instead. To configure the cleaning, pleas look
at lib.libcleaner
"""

__version__ = "2.0.1"
__author__ = "Sorawee Porncharoenwase"

import sys, os
sys.path.append(os.path.abspath("../.."))
from lib import preload
import pwikipedia as pywikibot
from lib import libcleaner

def _debug():
    print libcleaner.clean(conf.debugtext)

def main():
    for pagename in args:
        page = pywikibot.Page(site, pagename)
        page.put(libcleaner.clean(page.get()), conf.summary)

if __name__ == "__main__":
    args, site, conf = preload.pre(u"clean articles")
    try:
        #_debug()
        main()
    except:
        preload.posterror()
    else:
        preload.post()
