#!/usr/bin/python
# -*- coding: utf-8  -*-

import sys, os
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '../..')))

try: from lib import preload
except:
    print "เรียกใช้ไลบรารีไม่ได้ จบการทำงาน!"
    sys.exit()

import pwikipedia as pywikibot
from lib import libcleaner

def debug():
    print libcleaner.clean(u"""[[_asd_asd]]a
""")

def main():
    if args:
        for pagename in args:
            page = pywikibot.Page(site, pagename)
            page.put(libcleaner.clean(page.get()), u"เก็บกวาด")
    else:
        debug()

if __name__ == "__main__":
    args, site = preload.pre(u"เก็บกวาด")
    try: main()
    except: preload.posterror()
    preload.post()
