#!/usr/bin/python
# -*- coding: utf-8 -*-
"""
Remove "Recent death" template from the page which have been inserted
this tag for some time.
"""

from dateutil import relativedelta
from datetime import datetime
import re, sys, os, difflib
sys.path.append(os.path.abspath("../.."))
from lib import preload
import pwikipedia as pywikibot, pagegenerators

def _debug():
    NotImplemented

def main():
    gen = pagegenerators.ReferringPageGenerator(
                                    pywikibot.Page(site, conf.templateName),
                                    onlyTemplateInclusion = True)
    tlist = u"|".join(conf.templateList)
    pat = re.compile(ur"(?i)\{\{\s*(" + tlist + ur")\s*\}\}\s*")

    for page in gen:
        pywikibot.output(u">>> %s" % page.title())
        history = page.getVersionHistory()
        oldversion = page.getOldVersion(history[0][0])
        doerase = False
        found = False
        for cntversion, version in enumerate(history):
            if cntversion == 0:
                continue
            newversion = oldversion
            oldversion = page.getOldVersion(version[0])
            dobj = difflib.SequenceMatcher(a=oldversion, b=newversion)
            pywikibot.output(u"oldversion = %s" % version[0])
            for t in dobj.get_opcodes():
                if t[0] != "insert" or (not pat.search(newversion[t[3]:t[4]])):
                    continue
                    
                found = True
                dateadded = datetime.strptime(str(history[cntversion - 1][1]),
                                                "%Y-%m-%dT%H:%M:%SZ")
                datenow = datetime.today()
                dat = relativedelta.relativedelta(datenow, dateadded)
                pywikibot.output(str(dat))
                days = dat.days + dat.month*30 + dat.year*365
                if days > conf.daylimit:
                    doerase = True
                break
                
            if found:
                break
        if doerase:
            page.put(pat.sub(u"", page.get()), conf.summary)

if __name__ == "__main__":
    args, site, conf = preload.pre(u"remove recent death template",
                                    lock = True)
    try:
        #_debug()
        main()
    except:
        preload.posterror()
    preload.post()
