#!/usr/bin/python
# -*- coding: utf-8 -*-
"""Download dumpfile, extract pageview, and write table to wiki page."""

__version__ = "2.0.1"
__author__ = "Sorawee Porncharoenwase"

import urllib, re, os, sys
sys.path.append(os.path.abspath("../.."))
from lib import preload
import pwikipedia as pywikibot

def _debug():
    NotImplemented

def glob():
    pass

def main():
    def dlProgress(count, blockSize, totalSize):
        """Show download progress."""
        percent = int(count * blockSize * 100 / totalSize)
        sys.stdout.write("\r...%d%%" % percent)
        sys.stdout.flush()
        
    year = libdate.date.today().year
    month = libdate.date.today().month
    url = ("http://dumps.wikimedia.org/other/pagecounts-raw/%s/%s-%02d" % 
                                                    (year, year, int(month)))
    f = urllib.urlopen(url)
    content = f.read()
    filename = re.findall("pagecounts.*?\.gz", content)[-1]
    urllib.urlretrieve(os.path.join(url, filename),
                        "DLFILE.gz",
                        reporthook=dlProgress)
    os.system("gunzip --force DLFILE.gz")
    filename = "DLFILE"
    cbreak = False
    lines = []
    page = pywikibot.Page(site, conf.pagename)

    with open(filename, "r") as f:
        for line in f:
            if line.startswith(conf.sitecode):
                cbreak = True
                lines.append(line.split(" "))
            elif cbreak:
                break

    lines = sorted(lines, key=lambda x: int(x[2]), reverse=True)
    content = u""
    content = []
    ptr = -1
    while len(content) <= 100:
        ptr += 1
        name = eval('"%s"' % urllib.unquote(urllib.unquote(lines[ptr][1])))
        if ":" in name:
            continue
        if re.search("(?i)^undefined$", name):
            continue
        if name == u"th":
            continue
        content.append(u"|-\n| [[%s]] || %s\n" % (
                                            unicode(name).replace(u"_", u" "),
                                            unicode(lines[ptr][2])))
    content = u"""{| class = "wikitable"
|-
! บทความ !! จำนวนยอดผู้เข้าชม
""" + u"".join(content) + u"|}"
    pywikibot.output(content)
    page.put(content, conf.summary)
    
if __name__ == "__main__":
    args, site, conf = preload.pre(u"update pageview statistics", lock = True)
    try:
        glob()
        main()
    except:
        preload.posterror()
    else:
        preload.post()
