#!/usr/bin/python
# -*- coding: utf-8 -*-

import re, sys, time, os
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '../..')))

try: from lib import preload
except:
    print "เรียกใช้ไลบรารีไม่ได้ จบการทำงาน!"
    sys.exit()

import wikipedia as pywikibot
import pagegenerators, catlib, userlib, category

# constant
USER = u"User:Nullzerobot"
PAGEMAIN = USER + u"/บริการย้ายหมวดหมู่"
PAGEPENDING = USER + u"/บริการย้ายหมวดหมู่/หมวดหมู่ที่รอการพิจารณา"
PAGEREPORT =  USER + u"/รายงาน/บริการย้ายหมวดหมู่"
SIMULATE = False
VERIFYEDITCOUNT = 50
VERIFYTIME = 300000000
DONOTMOVE = False
FLUSHPENDING = "-pending"
LOCKFILE = "movecat.lock"
# end constant

site = pywikibot.getSite()

def domove(source, dest):
    pywikibot.output(u"ย้ายจาก " + source + " ไปยัง " + dest)
    if DONOTMOVE: return
    robot = category.CategoryMoveRobot(source, dest, batchMode = True,
        editSummary = u"", inPlace = False, titleRegex = None, withHistory = False)
    try:
        robot.run()
    except:
        preload.error()
        return
        
    pageCat = pywikibot.Page(site, u"หมวดหมู่:" + source)
    pageCat.put(u"{{bots|allow=Nullzerobot}}\n{{ลบ|บอตย้ายหมวดหมู่ไป[[:หมวดหมู่:" + dest + u"]] แล้ว}}", 
        u"ย้ายหมวดหมู่โดยบอต", force = True)

def verify(name, flag):
    if(flag): return True
    if name == u"N/A": return False
    pattern = re.compile(u"\{\{.*\|(.*)\}\}")
    result = pattern.match(name)
    if not result: return False
    name = result.group(1)
    user = userlib.User(site, name)
    if not user.isRegistered(): return False
    if user.editCount() < VERIFYEDITCOUNT: return False
    if user.isBlocked(): return False
    difftime = int(time.strftime("%Y%m%d%H%M%S", time.gmtime()))
    difftime -=  int(user.registrationTime())
    if(difftime < VERIFYTIME): return False
    return True

def catempty(title, flag):
    if(flag): return True
    cat = catlib.Category(site, 'Category:' + title)
    listOfArticles = cat.articlesList(recurse = False)
    return len(listOfArticles) == 0

def main():
    flag = False
    pywikibot.output(u"สคริปต์ย้ายหมวดหมู่เริ่มทำงาน ณ เวลา %s" % preload.getTime())
    
    if (len(sys.argv) > 1) and (sys.argv[1] == FLUSHPENDING):
        pywikibot.output(u"ย้ายหน้าที่รอพิจารณา")
        flag = True
        pageprocess = PAGEPENDING
        SUFFIX = u"\n|}"
    else:
        pageprocess = PAGEMAIN
        SUFFIX = u"\n|}\n\n{{/หมวดหมู่ที่รอการพิจารณา}}"
    
    pageMain = pywikibot.Page(site, pageprocess)
    text = pageMain.get(get_redirect = True)
    pre, post = text.split(u"!! เสนอโดย")
    
    if SUFFIX.strip() == post.strip():
        pywikibot.output("ไม่มีอะไรให้ทำ!")
        return
    
    summary = u"ย้ายหมวดหมู่ ณ เวลา "
    pageMain.put(pre + u"!! เสนอโดย" + SUFFIX, u"เริ่ม" + summary + preload.getTime())
    
    text = post

    pattern = re.compile(u"\|-.*\n\|(.*)\|\|.*\[\[:.*:(.*)\]\].*\[\[:.*:(.*)\]\].*\|\|(.*)\n")
    report = u""
    pending = u""
    isMove = False
    isPend = False
    
    while True:
        result = pattern.search(text)
        if not result: break
        vdate = result.group(1).strip()
        vfrom = result.group(2).strip()
        vto   = result.group(3).strip()
        vby   = result.group(4).strip()
        text = pattern.sub(u"", text, 1)
        if(not vby): vby = u"N/A"
        
        line = u"|-\n| "
        line += vdate
        line += u" || [[:หมวดหมู่:" 
        line += vfrom 
        line += u"]] || [[:หมวดหมู่:"
        line += vto
        line += u"]] || "
        line += vby

        if vdate and vfrom and vto and verify(vby, flag) and catempty(vto, flag):
            isMove = True
            domove(vfrom, vto)
            line += u" || "
            line += preload.getTime()
            line += u"\n"
            report += line
        else:
            isPend = True
            line += u"\n"
            pending += line

    text = text.strip()[:-len(SUFFIX)]
    
    if text != u"":
        pywikibot.output("Error!")
        pywikibot.output(text)
    
    if (not isMove) and (not isPend):
        pywikibot.output("ไม่มีอะไรให้ทำ (WTF)")
        return

    report += u"|}"
    pending += u"|}"
    p_end = re.compile(u"\|\}")
    
    if isMove:
        pageReport = pywikibot.Page(site, PAGEREPORT)
        text = pageReport.get(get_redirect = True)
        text = p_end.sub(u"", text, 1)
        text += report
        pageReport.put(text, summary + preload.getTime())

    if isPend:
        pagePending = pywikibot.Page(site, PAGEPENDING)
        text = pagePending.get(get_redirect = True)
        text = p_end.sub(u"", text, 1)
        text += pending
        pagePending.put(text, summary + preload.getTime())
        
    pywikibot.output(u"สคริปต์ย้ายหมวดหมู่หยุดทำงาน ณ เวลา %s" % preload.getTime())

if __name__ == "__main__":
    pywikibot.handleArgs("-log")
    if(SIMULATE): pywikibot.handleArgs("-simulate")
    lockfile = os.path.join("/tmp", LOCKFILE)
    
    if os.path.exists(lockfile):
        pywikibot.output(u"มีการล็อกอยู่อยู่")
        pywikibot.stopme()
        sys.exit()
    
    open(lockfile, 'w').close() 
    
    try:
        main()
    except:
        preload.error()
        sys.exit()
        
    try: os.remove(lockfile)
    except: pywikibot.output(u"ลบไฟล์ล็อกไม่ได้")
    pywikibot.stopme()
