#!/usr/bin/python
# -*- coding: utf-8 -*-

import sys, os
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '../..')))

try: from lib import preload
except:
    print "เรียกใช้ไลบรารีไม่ได้ จบการทำงาน!"
    sys.exit()

import pwikipedia as pywikibot

def main():
    NotImplemented

if __name__ == "__main__":
    args, site, conf = preload.pre(NotImplemented, lock = True)
    try: main()
    except: preload.posterror()
    preload.post()
