#!/usr/bin/python
# -*- coding: utf-8 -*-

import sys, os
sys.path.append(os.path.abspath("../.."))
from lib import preload
import pwikipedia as pywikibot

def _debug():
    NotImplemented

def glob():
    pass

def main():
    NotImplemented

if __name__ == "__main__":
    args, site, conf = preload.pre(NotImplemented, lock=True)
    try:
        glob()
        main()
    except:
        preload.posterror()
    else:
        preload.post()
