#!/bin/bash

cd "$(dirname $0)/../../config"
file="$(pwd)/data.cfg"
path="$(grep -o -P "(?<=PYWIKI: ).*" $file)"
python "$path/replace.py" -regex -subcats:หน้าที่ยังไม่ได้จัดหมวดหมู่ '\[\[[Cc]ategory:' '[[หมวดหมู่:'
python "$path/replace.py" -regex -cat:หน้าที่ยังไม่ได้จัดหมวดหมู่ '\[\[[Cc]ategory:' '[[หมวดหมู่:'
python "$path/replace.py" -regex -subcats:หน้าที่ยังไม่ได้จัดหมวดหมู่ '(?s)\{\{ต้องการหมวดหมู่\}\}\s*(?=.*\[\[หมวดหมู่:)' ''
python "$path/replace.py" -regex -cat:หน้าที่ยังไม่ได้จัดหมวดหมู่ '(?s)\{\{ต้องการหมวดหมู่\}\}\s*(?=.*\[\[หมวดหมู่:)' ''
